### PR TITLE
Finito 

### PR DESCRIPTION
**Pull request by kniak**

### CODE REVIEW

**Comment by nandanrao** [comment]
Great, but missing the second part!

Also, adding files via upload?? Cmon! Use the CLI!

**Comment by kniak** [comment]
Hola Nandan,

I know. I had some difficulties, could we arrange an office hour?

Thank you :)

Kostis.

P.S.: class said 3 weeks deadline

**Comment by nandanrao** [comment]
Yeah of course, anytime, just let me know! 

The email I got asked for "3 weeks from the 29th of October" -- just let me know if you want to change it, I'm completely neutral, I just want to set a date so we're all on the same page.

**Comment by kniak** [comment]
What about Monday?

Anytime except 15:00-18:00 is fine for me.

Ευχαριστώ.

Κωστής

**Pull request closed without merging**
